version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/themes/LoveIt"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 1
    labels:
      - "dependencies"
      - "npm"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 1
    labels:
      - "dependencies"
      - "gha"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "gomod"
    directory: "/themes/LoveIt"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 1
    labels:
      - "dependencies"
      - "go"
    groups:
      all:
        patterns:
          - "*"
